AWSTemplateFormatVersion: '2010-09-09'
Description: Creates S3 sync codebuild project
Resources:
  CodeBuildS3Sync:
    Type: AWS::CodeBuild::Project
    Properties:
      Description: !Sub 'Submit build jobs for ${GitHubRepoName} as part of CI/CD
        pipeline'
      ServiceRole: !Ref 'CodeBuildRoleArn'
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.6.5
        EnvironmentVariables:
          - Name: PROJECTNAME
            Value: !Sub '${GitHubRepoName}'
          - Name: GITHUBUSER
            Value: !Sub '${GitHubUser}'
          - Name: GITHUBTOKEN
            Value: !Sub '${GitHubOAuthToken}'
          - Name: SOURCEBRANCH
            Value: !Sub '${SourceRepoBranch}'
          - Name: ARTIFACT_BUCKET
            Value: !Ref 'ArtifactBucket'
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2

          phases:
            install:
              commands:
                - echo Entered the install phase...
                - apt-get update -y
                - sudo apt-get install zip gzip tar -y
                - pip3 install --upgrade pip
                - ln -s /usr/local/bin/pip /usr/bin/pip
            pre_build:
              commands:
                - echo Entered the pre_build phase...
                - echo Current directory is $CODEBUILD_SRC_DIR
                - ls -la
                - export dirname=${PWD##*/}
                - echo Directory name $dirname
                - cd ..
                - mv $dirname $PROJECTNAME
                - ls -la
                - cd $PROJECTNAME
                - git config --global url."https://github.com/".insteadOf "git@github.com:"
                - git init
                - git remote add origin https://$GITHUBTOKEN@github.com/$GITHUBUSER/$PROJECTNAME.git
                - git fetch
                - git checkout -ft origin/$SOURCEBRANCH
                - git submodule init
                - git submodule update --recursive
                - ls -lR
                - cd ..
                - echo Configuring aws cli...
                - aws configure set default.region us-west-2
            build:
              commands:
                - echo Entered the deploy phase...
                - cd $PROJECTNAME
                - aws s3 sync scripts s3://$ARTIFACT_BUCKET/$PROJECTNAME/scripts/
                - aws s3 sync packages s3://$ARTIFACT_BUCKET/$PROJECTNAME/packages/
                - aws s3 sync submodules s3://$ARTIFACT_BUCKET/$PROJECTNAME/submodules/
                - aws s3 sync templates s3://$ARTIFACT_BUCKET/$PROJECTNAME/templates/
                - exit $?

Parameters:
  GitHubUser:
    Description: Enter GitHub username of the repository owner
    Type: String
  GitHubRepoName:
    Description: Enter the repository name that should be monitored for changes
    Type: String
  SourceRepoBranch:
    Description: Enter the branch name to be monitored
    Type: String
  ReleaseBranch:
    Description: Enter the release branch name. On successfull build, above branch
      will be merged into this branch.
    Type: String
  GitHubOAuthToken:
    Description: Create a token with 'repo' and 'admin:repo_hook' permissions here
      https://github.com/settings/tokens
    Type: String
    NoEcho: 'true'
  ArtifactBucket:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Description: S3 bucket name used to store build artifacts.
    Type: String
  GitMergeLambda:
    Description: Name of the GitMerge Lambda function
    Type: String
  CodePipelineRoleArn:
    Description: Code Pipeline service role ARN
    Type: String
  CodeBuildRoleArn:
    Description: Code Build service role ARN
    Type: String
Outputs:
  CodeBuildProjectName:
    Description: CodeBuild S3 sync project name
    Value: !Ref 'CodeBuildS3Sync'
